development:
  archivist:
    - archivist1@example.com
  admin:
    - dlpierce@iu.edu
    - jhallida@iu.edu
    - jvwitten@iu.edu
    - aploshay@iu.edu
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  # Add roles for users here.
